# Markdownlint configuration for sdlc-quality
# See: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Disable line length rule (descriptions and documentation often need longer lines)
MD013: false

# Allow multiple blank lines (flexibility for readability)
MD012: false

# Allow trailing punctuation in headings
MD026: false

# Disable bare URL detection (URLs in documentation are common)
MD034: false

# Relax fenced code block rules (allow without surrounding blank lines in some contexts)
MD031: false

# Relax table formatting rules
MD058: false
MD060: false

# Allow hard tabs in code examples (some languages use tabs)
MD010: false

# Relax heading increment requirement (h4 after h2 is sometimes intentional)
MD001: false

# Allow inline HTML (needed for some markdown rendering contexts)
MD033: false
