#!/usr/bin/env bash
# Hook-Driven Test Framework Runner
# Generated by auto-harness plugin for sdlc-quality
#
# Commands:
#   init [--category X] [--tag Y] [--reset]  Initialize test run
#   next                                      Get next test action
#   validate "response"                       Validate response
#   skip                                      Skip current test
#   status                                    Show progress
#   report [--format md|json]                 Generate report
#   vars                                      Show saved variables
#   abort                                     Stop test run
#   reset                                     Clear state and results

set -euo pipefail

# Configuration - customize these paths for your project
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
STATE_FILE="$PROJECT_ROOT/.claude/test-state.json"
TESTS_FILE="$SCRIPT_DIR/tests.yaml"
REPORTS_DIR="$SCRIPT_DIR/reports"

# Ensure directories exist
mkdir -p "$(dirname "$STATE_FILE")"
mkdir -p "$REPORTS_DIR"

# ============================================================================
# Utility Functions
# ============================================================================

log() {
  echo "[runner] $*" >&2
}

die() {
  echo "ERROR: $*" >&2
  exit 1
}

# Get field from state JSON
get_state_field() {
  local field="$1"
  [[ -f "$STATE_FILE" ]] || return 0
  python3 -c "
import json, sys
try:
    with open('$STATE_FILE') as f:
        data = json.load(f)
    val = data.get('$field', '')
    if isinstance(val, (dict, list)):
        print(json.dumps(val))
    else:
        print(val if val is not None else '')
except Exception as e:
    print('', file=sys.stderr)
"
}

# Update state field
update_state() {
  local field="$1"
  local value="$2"
  python3 <<EOF
import json
try:
    with open('$STATE_FILE', 'r') as f:
        data = json.load(f)
except FileNotFoundError:
    data = {}
data['$field'] = $value
with open('$STATE_FILE', 'w') as f:
    json.dump(data, f, indent=2)
EOF
}

# Substitute variables in string
substitute_vars() {
  local text="$1"
  local vars_json
  vars_json=$(get_state_field "saved_vars")
  [[ -z "$vars_json" || "$vars_json" == "{}" ]] && echo "$text" && return

  python3 -c "
import json, re
text = '''$text'''
vars_data = json.loads('''$vars_json''')
for var, val in vars_data.items():
    text = text.replace(f'\${{{var}}}', str(val))
print(text)
"
}

# Get test by index from tests file
get_test() {
  local index="$1"
  python3 -c "
import json
import yaml

with open('$TESTS_FILE') as f:
    data = yaml.safe_load(f)
tests = data.get('tests', data) if isinstance(data, dict) else data
if $index < len(tests):
    print(json.dumps(tests[$index]))
else:
    print('null')
"
}

# Get total test count
get_test_count() {
  python3 -c "
import yaml

with open('$TESTS_FILE') as f:
    data = yaml.safe_load(f)
tests = data.get('tests', data) if isinstance(data, dict) else data
print(len(tests))
"
}

# ============================================================================
# Test Loading
# ============================================================================

load_tests() {
  local category_filter="${1:-}"
  local tag_filter="${2:-}"

  python3 <<EOF
import json
import sys

# Load tests
tests_file = '$TESTS_FILE'
try:
    import yaml
    with open(tests_file) as f:
        data = yaml.safe_load(f)
except ImportError:
    print("Error: PyYAML required for YAML tests. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

# Handle both formats: {tests: [...]} or just [...]
tests = data.get('tests', data) if isinstance(data, dict) else data

# Apply filters
category = '$category_filter' or None
tag = '$tag_filter' or None

filtered = []
for t in tests:
    if category and t.get('category') != category:
        continue
    if tag and tag not in t.get('tags', []):
        continue
    filtered.append(t)

print(json.dumps(filtered))
EOF
}

# ============================================================================
# Commands
# ============================================================================

cmd_init() {
  local category=""
  local tag=""
  local reset=false

  while [[ $# -gt 0 ]]; do
    case "$1" in
    --category)
      category="$2"
      shift 2
      ;;
    --tag)
      tag="$2"
      shift 2
      ;;
    --reset)
      reset=true
      shift
      ;;
    *) shift ;;
    esac
  done

  # Check for existing state
  if [[ -f "$STATE_FILE" && "$reset" != "true" ]]; then
    local mode
    mode=$(get_state_field "mode")
    if [[ "$mode" == "running" ]]; then
      local idx total
      idx=$(get_state_field "current_index")
      total=$(get_state_field "total_tests")
      echo "## Resuming Test Run"
      echo ""
      echo "Found existing test run in progress."
      echo "- **Progress:** $idx / $total"
      echo "- **Status:** Running"
      echo ""
      echo "Type \`next\` to continue, or use \`/run-tests --reset\` to start fresh."
      return 0
    fi
  fi

  # Load and filter tests
  local tests_json
  tests_json=$(load_tests "$category" "$tag")
  local total
  total=$(echo "$tests_json" | python3 -c "import json,sys; print(len(json.load(sys.stdin)))")

  if [[ "$total" -eq 0 ]]; then
    echo "## No Tests Found"
    echo ""
    echo "No tests match the specified filters."
    [[ -n "$category" ]] && echo "- Category: $category"
    [[ -n "$tag" ]] && echo "- Tag: $tag"
    return 1
  fi

  # Initialize state - pipe JSON through stdin to avoid heredoc escaping issues
  echo "$tests_json" | python3 -c "
import json
import sys
from datetime import datetime, timezone

tests = json.load(sys.stdin)
state = {
    'mode': 'running',
    'total_tests': len(tests),
    'current_index': 0,
    'current_test': tests[0] if tests else None,
    'filtered_tests': [t['id'] for t in tests],
    'results': [],
    'saved_vars': {},
    'filter_category': '$category' or None,
    'filter_tag': '$tag' or None,
    'started_at': datetime.now(timezone.utc).isoformat() + 'Z',
    'completed_at': None
}
with open('$STATE_FILE', 'w') as f:
    json.dump(state, f, indent=2)
"

  echo "## Test Suite Initialized"
  echo ""
  echo "**Total tests:** $total"
  [[ -n "$category" ]] && echo "**Category filter:** $category"
  [[ -n "$tag" ]] && echo "**Tag filter:** $tag"
  echo ""
  echo "Type \`next\` to begin testing."
}

cmd_next() {
  local mode
  mode=$(get_state_field "mode")

  if [[ "$mode" != "running" ]]; then
    echo "No active test run. Use \`/run-tests\` to start."
    return 1
  fi

  local idx total
  idx=$(get_state_field "current_index")
  total=$(get_state_field "total_tests")

  if [[ "$idx" -ge "$total" ]]; then
    update_state "mode" '"completed"'
    echo "## All Tests Complete"
    echo ""
    echo "All $total tests have been executed."
    echo "Type \`report\` to see the full results."
    return 0
  fi

  # Get test by index from file (not state)
  local test_json
  test_json=$(get_test "$idx")

  if [[ "$test_json" == "null" || -z "$test_json" ]]; then
    echo "Error: Could not load test at index $idx"
    return 1
  fi

  local test_id description category action
  test_id=$(echo "$test_json" | python3 -c "import json,sys; print(json.load(sys.stdin).get('id',''))")
  description=$(echo "$test_json" | python3 -c "import json,sys; print(json.load(sys.stdin).get('description',''))")
  category=$(echo "$test_json" | python3 -c "import json,sys; print(json.load(sys.stdin).get('category',''))")
  action=$(echo "$test_json" | python3 -c "import json,sys; print(json.load(sys.stdin).get('action',''))")

  # Substitute variables in action
  action=$(substitute_vars "$action")

  local num=$((idx + 1))

  echo "## Test $num/$total: $test_id"
  echo ""
  [[ -n "$category" ]] && echo "**Category:** $category"
  [[ -n "$description" ]] && echo "**Description:** $description"
  echo ""
  echo "### Action"
  echo ""
  echo "$action"
}

cmd_validate() {
  local response="$1"

  local mode
  mode=$(get_state_field "mode")

  if [[ "$mode" != "running" ]]; then
    echo "No active test run."
    return 1
  fi

  local idx total
  idx=$(get_state_field "current_index")
  total=$(get_state_field "total_tests")

  # Get test by index from file
  local test_json
  test_json=$(get_test "$idx")

  if [[ "$test_json" == "null" || -z "$test_json" ]]; then
    echo "Error: Could not load test at index $idx"
    return 1
  fi

  # Get test ID
  local test_id
  test_id=$(echo "$test_json" | python3 -c "import json,sys; print(json.load(sys.stdin).get('id',''))")

  # Validate response - use temp files to avoid heredoc escaping issues
  local tmp_test tmp_response
  tmp_test=$(mktemp)
  tmp_response=$(mktemp)
  echo "$test_json" >"$tmp_test"
  echo "$response" >"$tmp_response"

  local result
  result=$(python3 -c "
import json
import re

with open('$tmp_test') as f:
    test = json.load(f)
with open('$tmp_response') as f:
    response = f.read()

failures = []
captured_value = None

for exp in test.get('expect', []):
    if 'contains' in exp:
        if exp['contains'] not in response:
            failures.append(f\"Missing: '{exp['contains']}'\")

    if 'not_contains' in exp:
        if exp['not_contains'] in response:
            failures.append(f\"Unexpected: '{exp['not_contains']}'\")

    if 'regex' in exp:
        pattern = exp['regex']
        try:
            match = re.search(pattern, response)
            if not match:
                failures.append(f\"Pattern not found: '{pattern}'\")
            elif match.groups() and 'save_as' in test:
                captured_value = match.group(1)
        except re.error as e:
            failures.append(f\"Invalid regex '{pattern}': {e}\")

result = {
    'status': 'pass' if not failures else 'fail',
    'failures': failures,
    'captured_value': captured_value,
    'save_as': test.get('save_as')
}
print(json.dumps(result))
")

  rm -f "$tmp_test" "$tmp_response"

  local status failures_json captured_value save_as
  status=$(echo "$result" | python3 -c "import json,sys; print(json.load(sys.stdin)['status'])")
  failures_json=$(echo "$result" | python3 -c "import json,sys; print(json.dumps(json.load(sys.stdin)['failures']))")
  captured_value=$(echo "$result" | python3 -c "import json,sys; v=json.load(sys.stdin)['captured_value']; print(v if v else '')")
  save_as=$(echo "$result" | python3 -c "import json,sys; v=json.load(sys.stdin)['save_as']; print(v if v else '')")

  # Record result and advance state - pipe failures through stdin
  echo "$failures_json" | python3 -c "
import json
import sys
from datetime import datetime, timezone

failures = json.load(sys.stdin)

with open('$STATE_FILE', 'r') as f:
    state = json.load(f)

state['results'].append({
    'id': '$test_id',
    'status': '$status',
    'failures': failures,
    'timestamp': datetime.now(timezone.utc).isoformat() + 'Z'
})

# Save captured variable
save_as = '$save_as'
captured = '$captured_value'
if save_as and captured:
    state['saved_vars'][save_as] = captured

# Advance to next test
state['current_index'] += 1
if state['current_index'] >= state['total_tests']:
    state['mode'] = 'completed'
    state['completed_at'] = datetime.now(timezone.utc).isoformat() + 'Z'

with open('$STATE_FILE', 'w') as f:
    json.dump(state, f, indent=2)
"

  if [[ "$status" == "pass" ]]; then
    echo "## PASS: $test_id"
    [[ -n "$captured_value" ]] && echo "**Captured:** $save_as = $captured_value"
  else
    echo "## FAIL: $test_id"
    echo ""
    echo "**Failures:**"
    echo "$failures_json" | python3 -c "import json,sys; [print(f'  - {f}') for f in json.load(sys.stdin)]"
  fi

  echo ""

  local idx total
  idx=$(get_state_field "current_index")
  total=$(get_state_field "total_tests")

  if [[ "$idx" -lt "$total" ]]; then
    echo "Type \`next\` for the next test."
  else
    echo "All tests complete. Type \`report\` for results."
  fi
}

cmd_skip() {
  local mode
  mode=$(get_state_field "mode")

  if [[ "$mode" != "running" ]]; then
    echo "No active test run."
    return 1
  fi

  local test_json
  test_json=$(get_state_field "current_test")
  local test_id
  test_id=$(echo "$test_json" | python3 -c "import json,sys; print(json.load(sys.stdin).get('id',''))")

  # Record skip
  python3 <<EOF
import json
from datetime import datetime, timezone

with open('$STATE_FILE', 'r') as f:
    state = json.load(f)

state['results'].append({
    "id": "$test_id",
    "status": "skip",
    "failures": [],
    "timestamp": datetime.now(timezone.utc).isoformat() + "Z"
})

state['current_index'] += 1
if state['current_index'] < state['total_tests']:
    state['current_test'] = state['tests'][state['current_index']]
else:
    state['current_test'] = None
    state['mode'] = 'completed'
    state['completed_at'] = datetime.now(timezone.utc).isoformat() + "Z"

with open('$STATE_FILE', 'w') as f:
    json.dump(state, f, indent=2)
EOF

  echo "## SKIPPED: $test_id"
  echo ""
  echo "Type \`next\` for the next test."
}

cmd_status() {
  local mode
  mode=$(get_state_field "mode")

  if [[ ! -f "$STATE_FILE" ]]; then
    echo "No test run found. Use \`/run-tests\` to start."
    return 0
  fi

  python3 <<EOF
import json

with open('$STATE_FILE') as f:
    state = json.load(f)

results = state.get('results', [])
passed = sum(1 for r in results if r['status'] == 'pass')
failed = sum(1 for r in results if r['status'] == 'fail')
skipped = sum(1 for r in results if r['status'] == 'skip')
total = state.get('total_tests', 0)
current = state.get('current_index', 0)

print("## Test Progress")
print()
print(f"**Status:** {state.get('mode', 'unknown')}")
print(f"**Progress:** {current} / {total}")
print()
print("| Result | Count |")
print("|--------|-------|")
print(f"| Passed | {passed} |")
print(f"| Failed | {failed} |")
print(f"| Skipped | {skipped} |")

if state.get('filter_category'):
    print(f"\n**Filter:** category = {state['filter_category']}")
if state.get('filter_tag'):
    print(f"**Filter:** tag = {state['filter_tag']}")
EOF
}

cmd_report() {
  local format="markdown"

  while [[ $# -gt 0 ]]; do
    case "$1" in
    --format)
      format="$2"
      shift 2
      ;;
    *) shift ;;
    esac
  done

  if [[ ! -f "$STATE_FILE" ]]; then
    echo "No test results found."
    return 1
  fi

  python3 <<EOF
import json
from datetime import datetime, timezone

with open('$STATE_FILE') as f:
    state = json.load(f)

results = state.get('results', [])
passed = [r for r in results if r['status'] == 'pass']
failed = [r for r in results if r['status'] == 'fail']
skipped = [r for r in results if r['status'] == 'skip']
total = len(results)

format_type = '$format'

if format_type == 'json':
    report = {
        "generated_at": datetime.now(timezone.utc).isoformat() + "Z",
        "summary": {
            "total": total,
            "passed": len(passed),
            "failed": len(failed),
            "skipped": len(skipped),
            "pass_rate": len(passed) / total if total > 0 else 0
        },
        "results": results,
        "filters": {
            "category": state.get('filter_category'),
            "tag": state.get('filter_tag')
        }
    }
    print(json.dumps(report, indent=2))
else:
    # Markdown format
    print("# Test Execution Report")
    print()
    print(f"**Generated:** {datetime.now(timezone.utc).isoformat()}Z")
    print()
    print("## Summary")
    print()
    print("| Status | Count | Percentage |")
    print("|--------|-------|------------|")
    pct_pass = f"{len(passed)/total*100:.1f}%" if total > 0 else "0%"
    pct_fail = f"{len(failed)/total*100:.1f}%" if total > 0 else "0%"
    pct_skip = f"{len(skipped)/total*100:.1f}%" if total > 0 else "0%"
    print(f"| Passed | {len(passed)} | {pct_pass} |")
    print(f"| Failed | {len(failed)} | {pct_fail} |")
    print(f"| Skipped | {len(skipped)} | {pct_skip} |")
    print(f"| **Total** | **{total}** | **100%** |")

    if failed:
        print()
        print("## Failed Tests")
        print()
        for r in failed:
            print(f"### {r['id']}")
            print()
            if r.get('failures'):
                print("**Failures:**")
                for f in r['failures']:
                    print(f"- {f}")
            print()

    if passed:
        print()
        print("## Passed Tests")
        print()
        print("<details>")
        print(f"<summary>{len(passed)} tests passed (click to expand)</summary>")
        print()
        for r in passed:
            print(f"- {r['id']}")
        print()
        print("</details>")

    if skipped:
        print()
        print("## Skipped Tests")
        print()
        for r in skipped:
            print(f"- {r['id']}")
EOF
}

cmd_vars() {
  local vars
  vars=$(get_state_field "saved_vars")

  if [[ -z "$vars" || "$vars" == "{}" ]]; then
    echo "No variables captured yet."
    return 0
  fi

  echo "## Captured Variables"
  echo ""
  echo "$vars" | python3 -c "
import json, sys
data = json.load(sys.stdin)
for k, v in data.items():
    print(f'- **{k}:** {v}')
"
}

cmd_abort() {
  if [[ -f "$STATE_FILE" ]]; then
    update_state "mode" '"aborted"'
    echo "## Test Run Aborted"
    echo ""
    echo "Test execution has been stopped."
    echo "Type \`report\` to see partial results."
  else
    echo "No active test run to abort."
  fi
}

cmd_reset() {
  if [[ -f "$STATE_FILE" ]]; then
    rm -f "$STATE_FILE"
    echo "Test state cleared."
  else
    echo "No test state to clear."
  fi
}

# ============================================================================
# Main
# ============================================================================

main() {
  local cmd="${1:-help}"
  shift || true

  case "$cmd" in
  init) cmd_init "$@" ;;
  next) cmd_next ;;
  validate) cmd_validate "$*" ;;
  skip) cmd_skip ;;
  status) cmd_status ;;
  report) cmd_report "$@" ;;
  vars) cmd_vars ;;
  abort) cmd_abort ;;
  reset) cmd_reset ;;
  help | --help | -h)
    echo "Usage: runner.sh <command> [options]"
    echo ""
    echo "Commands:"
    echo "  init [--category X] [--tag Y] [--reset]  Initialize test run"
    echo "  next                                      Get next test"
    echo "  validate \"response\"                       Validate response"
    echo "  skip                                      Skip current test"
    echo "  status                                    Show progress"
    echo "  report [--format md|json]                 Generate report"
    echo "  vars                                      Show variables"
    echo "  abort                                     Stop test run"
    echo "  reset                                     Clear state"
    ;;
  *)
    die "Unknown command: $cmd"
    ;;
  esac
}

main "$@"
