#!/usr/bin/env bash
# Hook-Driven Test Framework - User Prompt Wrapper
# Generated by auto-harness plugin for sdlc-quality
#
# This script intercepts user prompts and routes test commands to the runner.
# When test mode is active, commands like "next", "skip", "validate" are
# transformed into test actions.

set -euo pipefail

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
STATE_FILE="$PROJECT_ROOT/.claude/test-state.json"
RUNNER="$PROJECT_ROOT/tests/functional/runner.sh"

# ============================================================================
# Utility Functions
# ============================================================================

# Output JSON with proper escaping using Python
json_replace() {
  local content="$1"
  python3 -c "
import json, sys
content = sys.stdin.read()
print(json.dumps({'replace': content}))
" <<<"$content"
}

# Output JSON to pass through unchanged
json_passthrough() {
  cat
}

# Check if test mode is currently active
is_test_mode() {
  [[ -f "$STATE_FILE" ]] || return 1
  local mode
  mode=$(python3 -c "
import json
try:
    with open('$STATE_FILE') as f:
        print(json.load(f).get('mode', ''))
except:
    print('')
")
  [[ "$mode" == "running" ]]
}

# ============================================================================
# Event Handlers
# ============================================================================

handle_user_prompt_submit() {
  local input
  input=$(cat)

  # Extract the prompt from input JSON
  local prompt
  prompt=$(echo "$input" | python3 -c "
import json, sys
try:
    data = json.load(sys.stdin)
    print(data.get('prompt', ''))
except:
    print('')
")

  # Normalize for command matching
  local normalized
  normalized=$(echo "$prompt" | tr '[:upper:]' '[:lower:]' | xargs)

  # Check if we're in test mode
  if is_test_mode; then
    case "$normalized" in
    # Next test
    next | n)
      local output
      output=$("$RUNNER" next 2>&1) || true
      json_replace "Execute the following test:

$output"
      return 0
      ;;

    # Skip current test
    skip | s)
      local output
      output=$("$RUNNER" skip 2>&1) || true
      json_replace "$output"
      return 0
      ;;

    # Validate response - extract everything after "validate "
    validate*)
      local response="${prompt#validate }"
      response="${response#v }" # Also handle shortcut
      local output
      output=$("$RUNNER" validate "$response" 2>&1) || true
      json_replace "$output"
      return 0
      ;;

    # Show status
    status)
      local output
      output=$("$RUNNER" status 2>&1) || true
      json_replace "$output"
      return 0
      ;;

    # Generate report
    report | report*)
      local -a format_args=()
      if [[ "$normalized" == *"json"* ]]; then
        format_args=(--format json)
      fi
      local output
      output=$("$RUNNER" report "${format_args[@]}" 2>&1) || true
      json_replace "$output"
      return 0
      ;;

    # Show captured variables
    vars)
      local output
      output=$("$RUNNER" vars 2>&1) || true
      json_replace "$output"
      return 0
      ;;

    # Abort test run
    abort | a)
      local output
      output=$("$RUNNER" abort 2>&1) || true
      json_replace "$output"
      return 0
      ;;

    # Help
    help | "?")
      json_replace "## Test Mode Commands

| Command | Shortcut | Description |
|---------|----------|-------------|
| \`next\` | \`n\` | Get and execute next test |
| \`skip\` | \`s\` | Skip current test |
| \`validate <response>\` | \`v <response>\` | Validate response |
| \`status\` | - | Show progress |
| \`report\` | - | Generate report |
| \`vars\` | - | Show captured variables |
| \`abort\` | \`a\` | Stop test run |

**Tip:** After Claude executes a test, copy the relevant response and use \`validate <response>\` to check it."
      return 0
      ;;
    esac
  fi

  # Not in test mode or not a test command - pass through
  echo "$input"
}

# ============================================================================
# Main
# ============================================================================

main() {
  local event="${1:-}"

  case "$event" in
  user-prompt-submit)
    handle_user_prompt_submit
    ;;
  *)
    # Unknown event - pass through
    cat
    ;;
  esac
}

main "$@"
