#!/usr/bin/env bash
# SDLC Report Generator
# Generates compliance reports in various formats (Markdown, JSON, SARIF)

set -euo pipefail

: "${SDLC_REPORT_DIR:=.sdlc-reports}"

# Generate Markdown report
generate_markdown_report() {
  local report_file="$SDLC_REPORT_DIR/report.md"
  local metadata_file="$SDLC_REPORT_DIR/metadata.json"

  if [[ ! -f "$metadata_file" ]]; then
    echo "Error: metadata.json not found"
    return 1
  fi

  local project_name
  local project_type
  local timestamp
  local score
  local status
  local critical_count
  local important_count
  local suggestion_count

  project_name=$(jq -r '.project_name' "$metadata_file")
  project_type=$(jq -r '.project_type' "$metadata_file")
  timestamp=$(jq -r '.timestamp' "$metadata_file")
  score=$(jq -r '.score' "$metadata_file")
  status=$(jq -r '.status' "$metadata_file")
  critical_count=$(jq -r '.critical_count' "$metadata_file")
  important_count=$(jq -r '.important_count' "$metadata_file")
  suggestion_count=$(jq -r '.suggestion_count' "$metadata_file")

  local status_emoji
  case "$status" in
    pass) status_emoji="✅" ;;
    warn) status_emoji="⚠️" ;;
    fail) status_emoji="❌" ;;
  esac

  cat > "$report_file" << EOF
# SDLC Compliance Audit Report

**Project**: $project_name
**Type**: $project_type
**Date**: $timestamp
**Overall Score**: $score/100 $status_emoji

## Summary

| Metric | Count |
|--------|-------|
| Critical (MUST) | $critical_count |
| Important (SHOULD) | $important_count |
| Suggestions (MAY) | $suggestion_count |

## Domain Scores

| Domain | Score | Status |
|--------|-------|--------|
EOF

  # Add domain scores
  local domains=("build" "quality" "testing" "ci" "security" "docs" "vcs" "release" "observability" "ai")

  for domain in "${domains[@]}"; do
    local domain_score_file="$SDLC_REPORT_DIR/${domain}-score.txt"
    if [[ -f "$domain_score_file" ]]; then
      local domain_score
      domain_score=$(cat "$domain_score_file")
      local domain_status
      if [[ $domain_score -ge 8 ]]; then
        domain_status="✅"
      elif [[ $domain_score -ge 5 ]]; then
        domain_status="⚠️"
      else
        domain_status="❌"
      fi
      echo "| ${domain^} | $domain_score/10 | $domain_status |" >> "$report_file"
    fi
  done

  # Add findings sections
  if [[ $critical_count -gt 0 ]]; then
    echo "" >> "$report_file"
    echo "## Critical Findings (MUST Fix)" >> "$report_file"
    echo "" >> "$report_file"

    for domain in "${domains[@]}"; do
      local findings_file="$SDLC_REPORT_DIR/${domain}-findings.txt"
      if [[ -f "$findings_file" ]]; then
        while IFS='|' read -r severity message file line; do
          if [[ "$severity" == "3" ]]; then
            local location=""
            [[ -n "$file" ]] && location=" ($file"
            [[ -n "$line" ]] && location="$location:$line"
            [[ -n "$location" ]] && location="$location)"
            echo "- **[$domain]** $message$location" >> "$report_file"
          fi
        done < "$findings_file"
      fi
    done
  fi

  if [[ $important_count -gt 0 ]]; then
    echo "" >> "$report_file"
    echo "## Important Findings (SHOULD Fix)" >> "$report_file"
    echo "" >> "$report_file"

    for domain in "${domains[@]}"; do
      local findings_file="$SDLC_REPORT_DIR/${domain}-findings.txt"
      if [[ -f "$findings_file" ]]; then
        while IFS='|' read -r severity message file line; do
          if [[ "$severity" == "2" ]]; then
            local location=""
            [[ -n "$file" ]] && location=" ($file"
            [[ -n "$line" ]] && location="$location:$line"
            [[ -n "$location" ]] && location="$location)"
            echo "- **[$domain]** $message$location" >> "$report_file"
          fi
        done < "$findings_file"
      fi
    done
  fi

  if [[ $suggestion_count -gt 0 ]]; then
    echo "" >> "$report_file"
    echo "## Suggestions (MAY Improve)" >> "$report_file"
    echo "" >> "$report_file"

    for domain in "${domains[@]}"; do
      local findings_file="$SDLC_REPORT_DIR/${domain}-findings.txt"
      if [[ -f "$findings_file" ]]; then
        while IFS='|' read -r severity message file line; do
          if [[ "$severity" == "1" ]]; then
            local location=""
            [[ -n "$file" ]] && location=" ($file"
            [[ -n "$line" ]] && location="$location:$line"
            [[ -n "$location" ]] && location="$location)"
            echo "- **[$domain]** $message$location" >> "$report_file"
          fi
        done < "$findings_file"
      fi
    done
  fi

  cat >> "$report_file" << 'EOF'

---

## About This Report

This report was generated by the [SDLC Standards Plugin](https://github.com/zircote/sdlc-quality).

### Severity Levels

- **MUST (Critical)**: Required for compliance. Blocks release.
- **SHOULD (Important)**: Strongly recommended. Should be addressed.
- **MAY (Suggestion)**: Optional improvement. Nice to have.

### Getting Help

For detailed guidance on each domain, refer to the [SDLC Standards Documentation](https://github.com/zircote/sdlc-quality/tree/main/skills).
EOF

  echo "Generated: $report_file"
}

# Generate JSON report
generate_json_report() {
  local report_file="$SDLC_REPORT_DIR/report.json"
  local metadata_file="$SDLC_REPORT_DIR/metadata.json"

  if [[ ! -f "$metadata_file" ]]; then
    echo "Error: metadata.json not found"
    return 1
  fi

  # Start with metadata
  local report
  report=$(cat "$metadata_file")

  # Add domain details
  local domains=("build" "quality" "testing" "ci" "security" "docs" "vcs" "release" "observability" "ai")
  local domain_scores="{}"
  local all_findings="[]"

  for domain in "${domains[@]}"; do
    local domain_score_file="$SDLC_REPORT_DIR/${domain}-score.txt"
    if [[ -f "$domain_score_file" ]]; then
      local domain_score
      domain_score=$(cat "$domain_score_file")
      domain_scores=$(echo "$domain_scores" | jq ". + {\"$domain\": $domain_score}")
    fi

    local findings_file="$SDLC_REPORT_DIR/${domain}-findings.txt"
    if [[ -f "$findings_file" ]]; then
      while IFS='|' read -r severity message file line; do
        local severity_name
        case "$severity" in
          3) severity_name="critical" ;;
          2) severity_name="important" ;;
          1) severity_name="suggestion" ;;
          *) severity_name="unknown" ;;
        esac

        local finding
        finding=$(jq -n \
          --arg domain "$domain" \
          --arg severity "$severity_name" \
          --arg message "$message" \
          --arg file "$file" \
          --arg line "$line" \
          '{domain: $domain, severity: $severity, message: $message, file: $file, line: $line}')

        all_findings=$(echo "$all_findings" | jq ". + [$finding]")
      done < "$findings_file"
    fi
  done

  # Combine into final report
  report=$(echo "$report" | jq \
    --argjson domain_scores "$domain_scores" \
    --argjson findings "$all_findings" \
    '. + {domain_scores: $domain_scores, findings: $findings}')

  echo "$report" | jq '.' > "$report_file"
  echo "Generated: $report_file"
}

# Generate SARIF report (for GitHub Code Scanning)
generate_sarif_report() {
  local report_file="$SDLC_REPORT_DIR/report.sarif"
  local metadata_file="$SDLC_REPORT_DIR/metadata.json"

  if [[ ! -f "$metadata_file" ]]; then
    echo "Error: metadata.json not found"
    return 1
  fi

  local project_name
  project_name=$(jq -r '.project_name' "$metadata_file")

  # SARIF 2.1.0 structure
  local sarif_template='{
    "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
    "version": "2.1.0",
    "runs": [{
      "tool": {
        "driver": {
          "name": "SDLC Compliance Check",
          "informationUri": "https://github.com/zircote/sdlc-quality",
          "version": "1.0.0",
          "rules": []
        }
      },
      "results": []
    }]
  }'

  local sarif
  sarif=$(echo "$sarif_template" | jq '.')

  local domains=("build" "quality" "testing" "ci" "security" "docs" "vcs" "release" "observability" "ai")
  local rule_index=0
  local rules="[]"
  local results="[]"

  for domain in "${domains[@]}"; do
    local findings_file="$SDLC_REPORT_DIR/${domain}-findings.txt"
    if [[ -f "$findings_file" ]]; then
      while IFS='|' read -r severity message file line; do
        local rule_id
        rule_id="SDLC-${domain^^}-$(printf '%03d' $rule_index)"
        local severity_level
        case "$severity" in
          3) severity_level="error" ;;
          2) severity_level="warning" ;;
          1) severity_level="note" ;;
          *) severity_level="none" ;;
        esac

        # Add rule
        local rule
        rule=$(jq -n \
          --arg id "$rule_id" \
          --arg name "$domain compliance" \
          --arg desc "$message" \
          '{
            id: $id,
            name: $name,
            shortDescription: {text: $desc},
            fullDescription: {text: $desc},
            helpUri: "https://github.com/zircote/sdlc-quality/tree/main/skills/\($name | split(" ")[0])"
          }')
        rules=$(echo "$rules" | jq ". + [$rule]")

        # Add result
        local result
        local uri="${file:-.}"
        local start_line="${line:-1}"

        result=$(jq -n \
          --arg ruleId "$rule_id" \
          --arg message "$message" \
          --arg level "$severity_level" \
          --arg uri "$uri" \
          --argjson line "$start_line" \
          '{
            ruleId: $ruleId,
            level: $level,
            message: {text: $message},
            locations: [{
              physicalLocation: {
                artifactLocation: {uri: $uri},
                region: {startLine: $line}
              }
            }]
          }')
        results=$(echo "$results" | jq ". + [$result]")

        rule_index=$((rule_index + 1))
      done < "$findings_file"
    fi
  done

  # Assemble final SARIF
  sarif=$(echo "$sarif" | jq \
    --argjson rules "$rules" \
    --argjson results "$results" \
    '.runs[0].tool.driver.rules = $rules | .runs[0].results = $results')

  echo "$sarif" | jq '.' > "$report_file"
  echo "Generated: $report_file"
}

# Generate PR comment body
generate_pr_comment_body() {
  local score
  local status
  local critical_count
  local important_count

  score=$(cat "$SDLC_REPORT_DIR/score.txt")
  status=$(cat "$SDLC_REPORT_DIR/status.txt")
  critical_count=$(cat "$SDLC_REPORT_DIR/critical-count.txt")
  important_count=$(cat "$SDLC_REPORT_DIR/important-count.txt")

  local status_emoji
  case "$status" in
    pass) status_emoji="✅" ;;
    warn) status_emoji="⚠️" ;;
    fail) status_emoji="❌" ;;
  esac

  cat << EOF
## $status_emoji SDLC Compliance Check

**Score**: $score/100 | **Status**: ${status^^}

| Critical | Important |
|----------|-----------|
| $critical_count | $important_count |

EOF

  if [[ $critical_count -gt 0 ]] || [[ $important_count -gt 0 ]]; then
    echo "<details>"
    echo "<summary>View Findings</summary>"
    echo ""

    if [[ -f "$SDLC_REPORT_DIR/report.md" ]]; then
      # Extract just the findings sections
      sed -n '/## Critical Findings/,/## About This Report/p' "$SDLC_REPORT_DIR/report.md" | head -n -2
    fi

    echo "</details>"
  fi

  echo ""
  echo "---"
  echo "*Generated by [SDLC Standards Plugin](https://github.com/zircote/sdlc-quality)*"
}

# Export functions
export -f generate_markdown_report generate_json_report generate_sarif_report generate_pr_comment_body
